/**
 * Mock 数据 - ASIN 主表
 * TODO: 后续替换为领星 ERP API 接口
 */
import type { AsinMaster } from '../types';

export const mockAsinMaster: AsinMaster[] = [
  {
    asin: 'B0A1234567',
    sku: 'SKU-US-001',
    title: 'Wireless Bluetooth Earbuds Pro',
    image_url: '',
    store_name: 'US-Store-Alpha',
    owner: '张三',
    team: 'A组',
    launch_date: '2025-12-01',
    lifecycle_stage: '稳定期',
    stable_grade: 'A',
    new_product_checkpoint: null,
    warning_level: '无',
    replenish_tag: '建议补货',
    is_clearance: false,
    is_eliminated: false,
  },
  {
    asin: 'B0A2345678',
    sku: 'SKU-US-002',
    title: 'USB-C Charging Cable 3-Pack',
    image_url: '',
    store_name: 'US-Store-Alpha',
    owner: '张三',
    team: 'A组',
    launch_date: '2026-03-01',
    lifecycle_stage: '新品期',
    stable_grade: null,
    new_product_checkpoint: 'D30',
    warning_level: '黄色',
    replenish_tag: '暂缓补货',
    is_clearance: false,
    is_eliminated: false,
  },
  {
    asin: 'B0A3456789',
    sku: 'SKU-US-003',
    title: 'Silicone Phone Case Ultra Slim',
    image_url: '',
    store_name: 'US-Store-Alpha',
    owner: '李四',
    team: 'A组',
    launch_date: '2025-06-15',
    lifecycle_stage: '稳定期',
    stable_grade: 'C',
    new_product_checkpoint: null,
    warning_level: '橙色',
    replenish_tag: '暂缓补货',
    is_clearance: false,
    is_eliminated: false,
  },
  {
    asin: 'B0A4567890',
    sku: 'SKU-US-004',
    title: 'LED Desk Lamp Adjustable',
    image_url: '',
    store_name: 'US-Store-Alpha',
    owner: '李四',
    team: 'A组',
    launch_date: '2024-09-10',
    lifecycle_stage: '清货',
    stable_grade: 'E',
    new_product_checkpoint: null,
    warning_level: '红色',
    replenish_tag: '禁止补货',
    is_clearance: true,
    is_eliminated: false,
  },
  {
    asin: 'B0A5678901',
    sku: 'SKU-UK-001',
    title: 'Kitchen Timer Digital Magnetic',
    image_url: '',
    store_name: 'UK-Store-Beta',
    owner: '王五',
    team: 'B组',
    launch_date: '2025-10-01',
    lifecycle_stage: '稳定期',
    stable_grade: 'B',
    new_product_checkpoint: null,
    warning_level: '无',
    replenish_tag: '建议补货',
    is_clearance: false,
    is_eliminated: false,
  },
  {
    asin: 'B0A6789012',
    sku: 'SKU-UK-002',
    title: 'Yoga Mat Non-Slip Premium',
    image_url: '',
    store_name: 'UK-Store-Beta',
    owner: '王五',
    team: 'B组',
    launch_date: '2026-02-15',
    lifecycle_stage: '新品期',
    stable_grade: null,
    new_product_checkpoint: 'D14',
    warning_level: '黄色',
    replenish_tag: '暂缓补货',
    is_clearance: false,
    is_eliminated: false,
  },
  {
    asin: 'B0A7890123',
    sku: 'SKU-UK-003',
    title: 'Portable Blender Mini USB',
    image_url: '',
    store_name: 'UK-Store-Beta',
    owner: '赵六',
    team: 'B组',
    launch_date: '2025-04-20',
    lifecycle_stage: '稳定期',
    stable_grade: 'S',
    new_product_checkpoint: null,
    warning_level: '无',
    replenish_tag: '建议补货',
    is_clearance: false,
    is_eliminated: false,
  },
  {
    asin: 'B0A8901234',
    sku: 'SKU-DE-001',
    title: 'Car Phone Mount Magnetic',
    image_url: '',
    store_name: 'DE-Store-Gamma',
    owner: '赵六',
    team: 'C组',
    launch_date: '2025-08-05',
    lifecycle_stage: '稳定期',
    stable_grade: 'D',
    new_product_checkpoint: null,
    warning_level: '橙色',
    replenish_tag: '暂缓补货',
    is_clearance: false,
    is_eliminated: false,
  },
  {
    asin: 'B0A9012345',
    sku: 'SKU-DE-002',
    title: 'Stainless Steel Water Bottle',
    image_url: '',
    store_name: 'DE-Store-Gamma',
    owner: '张三',
    team: 'C组',
    launch_date: '2024-03-01',
    lifecycle_stage: '淘汰',
    stable_grade: null,
    new_product_checkpoint: null,
    warning_level: '红色',
    replenish_tag: '禁止补货',
    is_clearance: false,
    is_eliminated: true,
  },
  {
    asin: 'B0A0123456',
    sku: 'SKU-DE-003',
    title: 'Wireless Charging Pad Fast',
    image_url: '',
    store_name: 'DE-Store-Gamma',
    owner: '李四',
    team: 'C组',
    launch_date: '2026-03-20',
    lifecycle_stage: '新品期',
    stable_grade: null,
    new_product_checkpoint: 'D7',
    warning_level: '无',
    replenish_tag: '暂缓补货',
    is_clearance: false,
    is_eliminated: false,
  },
  {
    asin: 'B0B1234567',
    sku: 'SKU-US-005',
    title: 'Smart Watch Band Replacement',
    image_url: '',
    store_name: 'US-Store-Alpha',
    owner: '张三',
    team: 'A组',
    launch_date: '2025-11-15',
    lifecycle_stage: '稳定期',
    stable_grade: 'B',
    new_product_checkpoint: null,
    warning_level: '无',
    replenish_tag: '建议补货',
    is_clearance: false,
    is_eliminated: false,
  },
  {
    asin: 'B0B2345678',
    sku: 'SKU-US-006',
    title: 'Screen Protector Tempered Glass',
    image_url: '',
    store_name: 'US-Store-Alpha',
    owner: '李四',
    team: 'A组',
    launch_date: '2025-07-01',
    lifecycle_stage: '清货',
    stable_grade: 'D',
    new_product_checkpoint: null,
    warning_level: '红色',
    replenish_tag: '禁止补货',
    is_clearance: true,
    is_eliminated: false,
  },
];
