/**
 * Mock 数据 - 任务表
 * TODO: 后续替换为任务中心 API
 */
import type { Task } from '../types';

export const mockTasks: Task[] = [
  {
    task_id: 'TASK-001',
    task_type: '广告优化',
    source_module: '广告诊断',
    asin: 'B0A3456789',
    store_name: 'US-Store-Alpha',
    owner: '李四',
    priority: '紧急',
    reason: 'ACOS 持续高于 40%，已超过阈值 7 天',
    suggested_action: '降低竞价 20%，暂停低效关键词',
    status: '待处理',
    due_date: '2026-04-01',
    created_at: '2026-03-28',
  },
  {
    task_id: 'TASK-002',
    task_type: '库存管理',
    source_module: '库存健康',
    asin: 'B0A1234567',
    store_name: 'US-Store-Alpha',
    owner: '张三',
    priority: '高',
    reason: 'FBA 库存仅剩 15 天可售天数',
    suggested_action: '立即发货补仓，建议补货 500 件',
    status: '处理中',
    due_date: '2026-04-02',
    created_at: '2026-03-27',
  },
  {
    task_id: 'TASK-003',
    task_type: '清货处理',
    source_module: 'ASIN生命周期',
    asin: 'B0A4567890',
    store_name: 'US-Store-Alpha',
    owner: '李四',
    priority: '高',
    reason: '连续 30 天利润为负，库存积压',
    suggested_action: '启动清货流程，降价 30% 或站外清货',
    status: '待处理',
    due_date: '2026-04-03',
    created_at: '2026-03-26',
  },
  {
    task_id: 'TASK-004',
    task_type: '新品跟进',
    source_module: 'ASIN生命周期',
    asin: 'B0A2345678',
    store_name: 'US-Store-Alpha',
    owner: '张三',
    priority: '中',
    reason: '新品 D30 检查点：转化率低于目标',
    suggested_action: '优化 Listing 主图和标题，检查定价竞争力',
    status: '待处理',
    due_date: '2026-04-05',
    created_at: '2026-03-29',
  },
  {
    task_id: 'TASK-005',
    task_type: '广告优化',
    source_module: '广告诊断',
    asin: 'B0A8901234',
    store_name: 'DE-Store-Gamma',
    owner: '赵六',
    priority: '中',
    reason: '广告有曝光无点击，CTR < 0.15%',
    suggested_action: '优化主图、调整投放匹配方式',
    status: '处理中',
    due_date: '2026-04-04',
    created_at: '2026-03-28',
  },
  {
    task_id: 'TASK-006',
    task_type: '补货决策',
    source_module: '库存健康',
    asin: 'B0A7890123',
    store_name: 'UK-Store-Beta',
    owner: '赵六',
    priority: '高',
    reason: 'S 级 ASIN，FBA 库存低于安全线',
    suggested_action: '加急补货 300 件，走空运',
    status: '待处理',
    due_date: '2026-04-01',
    created_at: '2026-03-29',
  },
  {
    task_id: 'TASK-007',
    task_type: '价格调整',
    source_module: '店铺健康',
    asin: 'B0B2345678',
    store_name: 'US-Store-Alpha',
    owner: '李四',
    priority: '紧急',
    reason: '清货 ASIN 价格仍高于竞品，清货速度慢',
    suggested_action: '降价至竞品价格 -10%，开启 coupon',
    status: '逾期',
    due_date: '2026-03-28',
    created_at: '2026-03-20',
  },
  {
    task_id: 'TASK-008',
    task_type: '新品跟进',
    source_module: 'ASIN生命周期',
    asin: 'B0A0123456',
    store_name: 'DE-Store-Gamma',
    owner: '李四',
    priority: '低',
    reason: '新品 D7 检查点：关注曝光量和首单',
    suggested_action: '确认广告已开启，检查类目节点是否正确',
    status: '已完成',
    due_date: '2026-03-30',
    created_at: '2026-03-27',
  },
  {
    task_id: 'TASK-009',
    task_type: '库存管理',
    source_module: '库存健康',
    asin: 'B0A9012345',
    store_name: 'DE-Store-Gamma',
    owner: '张三',
    priority: '紧急',
    reason: '淘汰 ASIN 仍有库存未清',
    suggested_action: '发起移除订单或转仓处理',
    status: '待处理',
    due_date: '2026-04-01',
    created_at: '2026-03-30',
  },
  {
    task_id: 'TASK-010',
    task_type: '广告优化',
    source_module: '广告诊断',
    asin: 'B0A5678901',
    store_name: 'UK-Store-Beta',
    owner: '王五',
    priority: '低',
    reason: 'ASIN 表现稳定，广告可放量',
    suggested_action: '提高预算 20%，拓展自动广告',
    status: '已完成',
    due_date: '2026-03-29',
    created_at: '2026-03-25',
  },
];
